### ISSUE TITLE
Unit 3 Section 16 Hacks Submission- Ava, Alexa, Lydia, Sri

### ISSUE THREAD

**Issue by avac54765** [SRIHITAKOTT1213/TeamBaddies#4]
Please comment your hacks for unit 3 section 16 below! Let us know if you have any questions! :))

**Comment by aaron-rub** [comment]
[Aaron's hacks](https://aaron-rub.github.io/FP/studentlesson/simulations)

**Comment by AlexKumar19** [comment]
[Alex's Hacks](https://alexkumar19.github.io/fastpages-APCSP/csp/316hacks)

**Comment by kaiden-dough** [comment]
[Kaiden's Hacks](https://kaiden-dough.github.io/fastpages/jupyter/week16/2022/12/13/Unit_3.16_HACKS.html)

**Comment by amayadvani** [comment]
[Amay's Hacks](https://amayadvani.github.io/fastpages/2022/12/13/316.html)

**Comment by gwang1224** [comment]
[Grace Wang Hacks](https://gwang1224.github.io/repository_1/trimester%202%20student%20teaching/2022/12/13/unit3-16.html#Hacks-Overview)

**Comment by LiavB2** [comment]
[Liav Bar's Hacks](https://liavb2.github.io/ominicient-lavebear/markdown/2022/12/13/3.16.html)

**Comment by JakeWarren2414** [comment]
[Jake's Hacks](https://jakewarren2414.github.io/FirstFastpages/.tri%202%20learning/2022/12/13/316.html)
My screenshot didn't work on my Fastpages for my quiz so here it is
![Flowchart](../images/SimulationQuiz.png)

**Comment by DavidVasilev1** [comment]
[David's Hacks](https://davidvasilev1.github.io/fastpages/markdown/trimester%202/notes/collegeboard/libraries/2022/12/16/3.14-18.html)

**Comment by clairehzhao** [comment]
[Claire Zhao's Hacks](https://clairehzhao.github.io/claire/student%20teaching/week16/jupyter/python/markdown/2022/12/13/unit3lesson16.html)

**Comment by hsinaDitaM** [comment]
[Mati Danish](https://hsinaditam.github.io/Danish_Cookies/simulations)

**Comment by ClaireChen3** [comment]
[Claire's Hacks](https://clairechen3.github.io/clairerepos/unit%203%20lessons/2022/12/13/316.html)

**Comment by SAnd353** [comment]
[Steven Zhu's Hacks](https://sand353.github.io/Blog/lesson_hacks/2022/12/13/316hacks.html)

**Comment by Nathan-Capule** [comment]
[Nathan's Hacks](https://github.com/Nathan-Capule/CSPFastpages/issues/25#issue-1497684117)

**Comment by PaarasPurohit** [comment]
[Paaras' Hacks](https://drive.google.com/file/d/1ZfM3hPCdLJNOBMCh0iSpvVMDvVcH27zb/view?usp=share_link)

**Comment by lunaiwa** [comment]
[Luna Iwazaki's HACKS](https://lunaiwa.github.io/iwazaki/unit%203/2022/12/13/Unit16HACKS.html)

**Comment by JakeWarren2414** [comment]
[Jake's Hacks](https://github.com/JakeWarren2414/FirstFastpages/issues/21)

**Comment by F1nnC** [comment]
[Finn's Hacks](https://f1nnc.github.io/mysite/.trimester%202%20student%20teaching/2022/12/13/hweight.html)

**Comment by B3nto4Lunch** [comment]
[Ederick Wong's Hacks]

**Comment by B3nto4Lunch** [comment]
[Ederick Wong's Hacks](https://github.com/B3nto4Lunch/Ederick-s-2022-2023-APCSP-Blog/issues/12)

**Comment by bushku** [comment]
[Shruthi's Hacks](https://bushku.github.io/APCSP_1/2022/12/13/simulations.html)

**Comment by yashakhoshini** [comment]
[yasha's hacks](https://yashakhoshini.github.io/yasha-fastpages/python/hacks/2022/12/14/section-16-hacks.html)

**Comment by realethantran** [comment]
[Ethan's Hacks](https://realethantran.github.io/fastpages_EthanT/unit%203/sections%2016/hacks/2022/12/13/Unit-3-Section-16-Hacks.html)

**Comment by safinsingh** [comment]
[Safin's hacks](https://safinsingh.github.io/fastpages-apcsp/jupyter/2022/12/13/316hacks.html)

**Comment by Jw95z** [comment]
[Jeongwoo Lee's Hack](https://jw95z.github.io/JeongWooLee/2022/12/13/16.html)

**Comment by TaiyoI** [comment]
[Taiyo's hacks](https://taiyoi.github.io/Compsci22/2022/12/13/Lesson16Notes&Hacks.html) (meant to be 3.16)

**Comment by LukaVDB** [comment]
[luka hacks](https://lukavdb.github.io/Project-1/studentlesson/simulations)

**Comment by nikhilc3** [comment]
https://www.loom.com/share/6c0c97f0abdf4cf8970f91f52b33589e

**Comment by JishnuS420** [comment]
Jishnu Singiresu, Period 3

[Homework and Notes](https://github.com/JishnuS420/CSP-tri1/issues/19#issue-1499332719)

**Comment by antonyrc6** [comment]
[Antony's hack](https://antonyrc6.github.io/Antony-s-fast-page/notebook/2022/12/13/Lesson-3.16-hack.html)
